### PR TITLE
Update for Better index for usability via the main Github Page

### PR DESCRIPTION
**Pull request by MinecraftChromeDev**
The main purpose of making an updated index was so people who wished to make a fork of the repository can easily do so or for people who simply just wanted to press the play button without having to find the play.html. my mistake was that i accidentally left MY repo in the index leading it to mine on accident however i just fixed this.

### CODE REVIEW

**Comment by Naievil** [comment]
Do you mind adjusting the title for clarity and collapsing your commits into one?

**Comment by MinecraftChromeDev** [comment]
Im not sure how to merge the commits does it have to be done? :<

**Comment by Naievil** [comment]
`git reset --soft <last-good-commit>` 
Then add all files that have changed
Then commit and push to this branch with --force

**Comment by MinecraftChromeDev** [comment]
well im not at home right now so ill make sure to do it when i get a chance! ill make this as a draft for now, thank you!

**Comment by MinecraftChromeDev** [comment]
actually its not even that big of a change, im just going to close it

**Pull request closed without merging**
